'use strict';

// Privater Testkatalog für den ersten Durchlauf.
// Vor Veröffentlichung entfernen oder durch öffentliche Fragen ersetzen.
// TODO: Alle Koordinaten vor dem echten Spiel geokodieren und prüfen.
const QUESTIONS = [
  {
    id: 'wo-sind-wir-gerade',
    questionText: 'Wo sind wir gerade?',
    subtitle: 'Test-Durchlauf',
    targetName: 'Aktueller Ort / Weidmannstraße 6',
    targetAddress: 'Weidmannstraße 6, 80997 München',
    targetLatitude: 48.184,
    targetLongitude: 11.507,
    mapView: 'germany',
    mapType: 'germany',
    mapLabel: 'Ganz Deutschland',
    category: 'Adresse',
    difficulty: 'mittel',
    isPrivateQuestion: true,
  },
  {
    id: 'richi-frueher-gewohnt',
    questionText: 'Wo hat Richi früher gewohnt?',
    subtitle: '',
    targetName: 'Richis frühere Adresse',
    targetAddress: 'Winterstraße 12, 85241 Hebertshausen',
    targetLatitude: 48.294,
    targetLongitude: 11.466,
    mapView: 'hebertshausen',
    mapType: 'hebertshausen',
    mapLabel: 'Ganz Hebertshausen',
    category: 'Adresse',
    difficulty: 'schwer',
    isPrivateQuestion: true,
  },
  {
    id: 'spanien-urlaubs-airbnb',
    questionText: 'Wo war unser Spanien-Urlaubs-Airbnb?',
    subtitle: '',
    targetName: 'Spanien-Airbnb',
    targetAddress: 'Camí Ral, 69, 08330 Barcelona, Spanien',
    targetLatitude: 41.49,
    targetLongitude: 2.36,
    mapView: 'spain',
    mapType: 'spain',
    mapLabel: 'Ganz Spanien',
    category: 'Urlaub',
    difficulty: 'mittel',
    isPrivateQuestion: true,
  },
  {
    id: 'therme-erding',
    questionText: 'Wo liegt die Therme Erding?',
    subtitle: '',
    targetName: 'Therme Erding',
    targetAddress: 'Thermenallee 1-5, 85435 Erding',
    targetLatitude: 48.2908,
    targetLongitude: 11.889,
    mapView: 'erding',
    mapType: 'erding',
    mapLabel: 'Ganz Erding',
    category: 'Sehenswürdigkeit',
    difficulty: 'leicht',
    isPrivateQuestion: true,
  },
  {
    id: 'europa-park',
    questionText: 'Wo liegt der Europa-Park?',
    subtitle: '',
    targetName: 'Europa-Park',
    targetAddress: 'Europa-Park-Straße 2, 77977 Rust',
    targetLatitude: 48.2681,
    targetLongitude: 7.7209,
    mapView: 'germany',
    mapType: 'germany',
    mapLabel: 'Ganz Deutschland',
    category: 'Freizeitpark',
    difficulty: 'mittel',
    isPrivateQuestion: true,
  },
];

module.exports = {
  QUESTIONS,
};
