'use strict';

const ORIGINAL_SOURCE_URL =
  'https://www.joyn.de/play/serien/das-1prozent-quiz-wie-clever-ist-deutschland/4-12-zauberwuerfel-speed-dating-und-ein-anruf-von-mama';

const PERCENT_QUIZ_QUESTIONS = [
  {
    id: 'percent-30',
    label: '30% Frage',
    percent: 30,
    multiplier: 2,
    clipSrc: '/clips/prozentquiz/30.mp4',
    solutionImageSrc: '/clips/prozentquiz/solutions/30.png',
    solutionTitle: 'Lösung 30% Frage',
    correctAnswer: null,
    originalSourceUrl: ORIGINAL_SOURCE_URL,
    originalStart: '55:40',
    originalEnd: '56:47',
    answerType: 'choice',
    options: ['A', 'B', 'C', 'D'],
    adminTitle: '30% Frage',
    playerInstruction: 'Wähle A, B, C oder D und logge deine Antwort ein.',
  },
  {
    id: 'percent-25',
    label: '25% Frage',
    percent: 25,
    multiplier: 2.5,
    clipSrc: '/clips/prozentquiz/25.mp4',
    solutionImageSrc: '/clips/prozentquiz/solutions/25.png',
    solutionTitle: 'Lösung 25% Frage',
    correctAnswer: null,
    originalSourceUrl: ORIGINAL_SOURCE_URL,
    originalStart: '1:00:53',
    originalEnd: '1:01:50',
    answerType: 'number',
    options: [],
    adminTitle: '25% Frage',
    playerInstruction: 'Gib eine Zahl ein und logge deine Antwort ein.',
  },
  {
    id: 'percent-20',
    label: '20% Frage',
    percent: 20,
    multiplier: 3,
    clipSrc: '/clips/prozentquiz/20.mp4',
    solutionImageSrc: '/clips/prozentquiz/solutions/20.png',
    solutionTitle: 'Lösung 20% Frage',
    correctAnswer: null,
    originalSourceUrl: ORIGINAL_SOURCE_URL,
    originalStart: '1:03:28',
    originalEnd: '1:04:10',
    answerType: 'choice',
    options: ['A', 'B', 'C', 'D'],
    adminTitle: '20% Frage',
    playerInstruction: 'Wähle A, B, C oder D und logge deine Antwort ein.',
  },
  {
    id: 'percent-15',
    label: '15% Frage',
    percent: 15,
    multiplier: 4,
    clipSrc: '/clips/prozentquiz/15.mp4',
    solutionImageSrc: '/clips/prozentquiz/solutions/15.png',
    solutionTitle: 'Lösung 15% Frage',
    correctAnswer: null,
    originalSourceUrl: ORIGINAL_SOURCE_URL,
    originalStart: '1:06:26',
    originalEnd: '1:07:38',
    answerType: 'number',
    options: [],
    adminTitle: '15% Frage',
    playerInstruction: 'Gib eine Zahl ein und logge deine Antwort ein.',
  },
  {
    id: 'percent-10',
    label: '10% Frage',
    percent: 10,
    multiplier: 5,
    clipSrc: '/clips/prozentquiz/10.mp4',
    solutionImageSrc: '/clips/prozentquiz/solutions/10.png',
    solutionTitle: 'Lösung 10% Frage',
    correctAnswer: null,
    originalSourceUrl: ORIGINAL_SOURCE_URL,
    originalStart: '1:09:38',
    originalEnd: '1:10:53',
    answerType: 'choice',
    options: ['A', 'B', 'C', 'D', 'E', 'F'],
    adminTitle: '10% Frage',
    playerInstruction: 'Wähle A, B, C, D, E oder F und logge deine Antwort ein.',
  },
  {
    id: 'percent-5',
    label: '5% Frage',
    percent: 5,
    multiplier: 5.5,
    clipSrc: '/clips/prozentquiz/5.mp4',
    solutionImageSrc: '/clips/prozentquiz/solutions/5.png',
    solutionTitle: 'Lösung 5% Frage',
    correctAnswer: null,
    originalSourceUrl: ORIGINAL_SOURCE_URL,
    originalStart: '1:18:12',
    originalEnd: '1:19:06',
    answerType: 'grid',
    options: [],
    gridRows: 4,
    gridCols: 3,
    adminTitle: '5% Frage',
    playerInstruction: 'Wähle ein Feld im 3x4-Raster und logge deine Antwort ein.',
  },
  {
    id: 'percent-1',
    label: '1% Frage',
    percent: 1,
    multiplier: 6,
    clipSrc: '/clips/prozentquiz/1.mp4',
    solutionImageSrc: '/clips/prozentquiz/solutions/1.png',
    solutionTitle: 'Lösung 1% Frage',
    correctAnswer: null,
    originalSourceUrl: ORIGINAL_SOURCE_URL,
    originalStart: '1:23:40',
    originalEnd: '1:24:41',
    answerType: 'number',
    options: [],
    adminTitle: '1% Frage',
    playerInstruction: 'Gib eine Zahl ein und logge deine Antwort ein.',
  },
];

module.exports = {
  ORIGINAL_SOURCE_URL,
  PERCENT_QUIZ_QUESTIONS,
};
